name: Publish to NPM

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the `main` branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the library
      run: npm run build

    - name: Configure Git identity
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Bump version and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token to allow pushing back to the repo
      run: |
        npm version patch -m "Bump version to %s [skip ci]"
        git push origin main --follow-tags # Push changes and tags back to the repository

    - name: Publish Private Package to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use the NPM token from GitHub Secrets
      run: npm publish --access restricted